services:
  - type: web
    name: documation-payslips-render
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MAX_FILE_MB
        value: "50"
